### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by knotsite15** [Soluto/webdriverio-zap-proxy#16]
When I run docker-compose build, I get the below error.
Building black-box
Step 1/10 : FROM node:latest
 ---> 932354abf0cc
Step 2/10 : WORKDIR /usr/src/app
 ---> Using cache
 ---> c6564a719b21
Step 3/10 : COPY install_dependencies.sh ./
 ---> Using cache
 ---> d96f98249366
Step 4/10 : RUN ./install_dependencies.sh
 ---> Using cache
 ---> b3fbebdfa97b
Step 5/10 : COPY package.json /tmp
 ---> Using cache
 ---> 2b0614264ccf
Step 6/10 : COPY yarn.lock /tmp
 ---> Using cache
 ---> 6657aa080cb7
Step 7/10 : RUN cd /tmp && yarn install
 ---> Running in 89ce45546a1e
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
(node:6) **[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.**
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /tmp/node_modules/fibers: Command failed.

**Comment by omerlh** [comment]
Thanks for reporting! I fixed it, let me know if it worked for you - if not, please reopen
